# Site settings
title: Transport it!
description: "Notes on machine learning and other subjects"
url: "https://edmophia.github.io/"
author:
  name: "Sung-Yub Kim"
  email: "edmophia@snu.ac.kr"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
mathjax: true
highlighter: rouge
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
mermaid:
  src: /js/mermaid.js

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-mermaid

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
